language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  fast_finish: true

before_script:
  - ./scripts/travis
  - composer init --no-interaction --stability=dev
  - composer require "photon/utils-viewdumper:dev-master"
  - cp vendor/photon/utils-viewdumper/phpunit.xml .

script: phpunit -c phpunit.xml
